#pragma once

// 마스터 설정
#define MASTER_LEFT

// 탭/홀드
#define TAPPING_TERM 162
#define TAPPING_TERM_PER_KEY
#define TAPPING_TERM_THUMB 125
#define PERMISSIVE_HOLD
#define HOLD_ON_OTHER_KEY_PRESS

// 원샷 키
#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 2000

// 조이스틱
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define ANALOG_JOYSTICK_X_AXIS_PIN GP27
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP26
#define ANALOG_JOYSTICK_SPEED_REGULATOR 13
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_INVERT_Y
#define POINTING_DEVICE_ROTATION_270

// RGB Matrix
#define DRIVER_LED_TOTAL 54
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 150
#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_ALPHAS_MODS

// RGB 효과 허용
#define ENABLE_RGB_MATRIX_ALPHAS_MODS
#define ENABLE_RGB_MATRIX_BAND_SAT
#define ENABLE_RGB_MATRIX_BAND_VAL
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN

// OLED
#define OLED_DRIVER SSD1306

// EEPROM
#define RP2040_EEPROM_SIZE 4096
