# MCU
MCU = RP2040
BOOTLOADER = rp2040

# RGB 설정
RGB_MATRIX_ENABLE = yes
RGBLIGHT_ENABLE = no
WS2812_DRIVER = vendor

# OLED 설정
OLED_ENABLE = yes
OLED_DRIVER = ssd1306

# 조이스틱 (아날로그 스틱)
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = analog_joystick
SPLIT_POINTING_ENABLE = yes


# 스플릿 키보드
SPLIT_KEYBOARD = yes
SPLIT_TRANSPORT_MIRROR = yes

# 기타 기능
EXTRAKEY_ENABLE = yes
WPM_ENABLE = yes
OS_DETECTION_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
COMBO_ENABLE = yes
CONSOLE_ENABLE = yes

# QMK CLI용
INTROSPECTION_KEYMAP_C = keymap.c
