COMBO_ENABLE = yes
INTROSPECTION_KEYMAP_C = keymap.c
MOUSEKEY_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306

SERIAL_DRIVER = vendor
JOYSTICK_ENABLE = yes
POINTING_DEVICE_DRIVER = analog_joystick
SPLIT_POINTING_ENABLE = yes

CONSOLE_ENABLE = yes
EXTRAKEY_ENABLE = yes
WPM_ENABLE = yes